language: scala

scala:
   - 2.11.8

jdk:
   - oraclejdk8

services:
  - docker

before_install:
  - docker-compose up -d

script:
  - sbt test

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot